# Meta Data for SEO

## Homepage
title = "ELO Dogfight Challenge"
titleSeparator = "-"
titleAddition = "1v1 guns only DCS World competition"
description = "1v1 guns only DCS World competition."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["cellules-rapaces_og.png"]
ogLocale = "fr_FR"
domainTLD = "elodogfight.cellules-rapaces.fr"
titleHome = "ELO Dogfight"

## Twitter Cards
twitterSite = "@CellulesRapaces"
twitterCreator = "@Couby40"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Cellules Rapaces"
schemaAuthor = "CoubyStark"
schemaAuthorTwitter = "https://twitter.com/Couby40"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/couby/"
schemaAuthorGitHub = "https://github.com/Couby"
schemaLocale = "fr-FR"
schemaLogo = "logo-cellules-rapaces.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "cellules-rapaces.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/CellulesRapaces"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/Cellules-Rapaces"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 90
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer1 = '<small class="d-block mb-3 text-muted text-center">&copy; 2004–2022 Cellules Rapaces </br>par CoubyStark</small>'
footer2 = 'Les défis Rapaces'
footer3 = 'A propos'
footer4 = 'Réseaux sociaux'
footer5 = '⬆️'

# Feed
copyRight = "Copyright (c) 2004–2022 CoubyStark"

# Alert
alert = false
alertDismissable = true
alertText = "Texte dans l'alerte ! <a class=\"alert-link stretched-link\" href=\"https://lien/\">Texte du lien</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/Cellules-Rapaces/eloDogfight"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["resultats"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = true
  docsVersioning = false
  fullWidth = true
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
